/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dietapp;

/**
 *
 * @author megan
 */
public class DietGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DietGUI.class.getName());

    /**
     * Creates new form DietGUI
     */
    public DietGUI() {
        initComponents();
        mainPagePnl.setVisible(true);
        mealEntryPnl.setVisible(false);
        tablePnl.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mealEntryPnl = new javax.swing.JPanel();
        mealNameLbl = new javax.swing.JLabel();
        mealNameTF = new javax.swing.JTextField();
        caloriesLbl = new javax.swing.JLabel();
        caloriesTF = new javax.swing.JTextField();
        mealTypeLbl = new javax.swing.JLabel();
        mealTypeCmb = new javax.swing.JComboBox<>();
        dateLbl = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        summaryBtn = new javax.swing.JButton();
        dietTrackerLbl = new javax.swing.JLabel();
        back1Btn = new javax.swing.JButton();
        tablePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealEntryTbl = new javax.swing.JTable();
        summaryLbl = new javax.swing.JLabel();
        totalCaloriesLbl = new javax.swing.JLabel();
        macrosLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        mainPagePnl = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        addMealBtn = new javax.swing.JButton();
        viewSummaryBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        sentenceLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mealEntryPnl.setBackground(new java.awt.Color(210, 244, 234));
        mealEntryPnl.setForeground(new java.awt.Color(255, 255, 255));

        mealNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mealNameLbl.setForeground(new java.awt.Color(51, 51, 51));
        mealNameLbl.setText("Meal Name:");

        caloriesLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caloriesLbl.setForeground(new java.awt.Color(51, 51, 51));
        caloriesLbl.setText("Calories:");

        mealTypeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mealTypeLbl.setForeground(new java.awt.Color(51, 51, 51));
        mealTypeLbl.setText("Meal Type:");

        mealTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Lunch", "Dinner", "Snack" }));
        mealTypeCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealTypeCmbActionPerformed(evt);
            }
        });

        dateLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(51, 51, 51));
        dateLbl.setText("Date:");

        addBtn.setBackground(new java.awt.Color(142, 218, 114));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 102, 51));
        addBtn.setText("Add");
        addBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        addBtn.setBorderPainted(false);

        updateBtn.setBackground(new java.awt.Color(142, 218, 114));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(0, 102, 51));
        updateBtn.setText("Update");
        updateBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        updateBtn.setBorderPainted(false);

        deleteBtn.setBackground(new java.awt.Color(142, 218, 114));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 102, 51));
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        deleteBtn.setBorderPainted(false);

        summaryBtn.setBackground(new java.awt.Color(142, 218, 114));
        summaryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        summaryBtn.setForeground(new java.awt.Color(0, 102, 51));
        summaryBtn.setText("View Summary");
        summaryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        summaryBtn.setBorderPainted(false);
        summaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBtnActionPerformed(evt);
            }
        });

        dietTrackerLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dietTrackerLbl.setForeground(new java.awt.Color(0, 102, 5));
        dietTrackerLbl.setText("Diet Tracker");

        back1Btn.setBackground(new java.awt.Color(142, 218, 114));
        back1Btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back1Btn.setForeground(new java.awt.Color(0, 102, 51));
        back1Btn.setText("Back");
        back1Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        back1Btn.setBorderPainted(false);
        back1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mealEntryPnlLayout = new javax.swing.GroupLayout(mealEntryPnl);
        mealEntryPnl.setLayout(mealEntryPnlLayout);
        mealEntryPnlLayout.setHorizontalGroup(
            mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealEntryPnlLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(summaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(back1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mealEntryPnlLayout.createSequentialGroup()
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mealEntryPnlLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caloriesLbl)
                            .addComponent(mealTypeLbl)
                            .addComponent(mealNameLbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealEntryPnlLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mealEntryPnlLayout.createSequentialGroup()
                        .addComponent(dietTrackerLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mealEntryPnlLayout.createSequentialGroup()
                        .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caloriesTF)
                            .addComponent(mealNameTF))
                        .addGap(58, 58, 58))
                    .addGroup(mealEntryPnlLayout.createSequentialGroup()
                        .addComponent(mealTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mealEntryPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        mealEntryPnlLayout.setVerticalGroup(
            mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealEntryPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dietTrackerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealNameLbl))
                .addGap(21, 21, 21)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caloriesLbl)
                    .addComponent(caloriesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealTypeLbl)
                    .addComponent(mealTypeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn))
                .addGap(18, 18, 18)
                .addGroup(mealEntryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back1Btn)
                    .addComponent(summaryBtn))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tablePnl.setBackground(new java.awt.Color(210, 244, 234));
        tablePnl.setForeground(new java.awt.Color(255, 255, 255));

        mealEntryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meal Name", "Meal Type", "Calories", "Date"
            }
        ));
        mealEntryTbl.setPreferredSize(new java.awt.Dimension(328, 138));
        jScrollPane1.setViewportView(mealEntryTbl);

        summaryLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        summaryLbl.setForeground(new java.awt.Color(0, 102, 5));
        summaryLbl.setText("Meal Entry Summary:");

        totalCaloriesLbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        totalCaloriesLbl.setForeground(new java.awt.Color(51, 51, 51));
        totalCaloriesLbl.setText("Total Calories:");

        macrosLbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        macrosLbl.setForeground(new java.awt.Color(51, 51, 51));
        macrosLbl.setText("Macronutrients Breakdown:");

        backBtn.setBackground(new java.awt.Color(142, 218, 114));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 102, 51));
        backBtn.setText("Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        backBtn.setBorderPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablePnlLayout = new javax.swing.GroupLayout(tablePnl);
        tablePnl.setLayout(tablePnlLayout);
        tablePnlLayout.setHorizontalGroup(
            tablePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePnlLayout.createSequentialGroup()
                .addGroup(tablePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablePnlLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(tablePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCaloriesLbl)
                            .addComponent(macrosLbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tablePnlLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(summaryLbl)
                .addGap(89, 89, 89))
        );
        tablePnlLayout.setVerticalGroup(
            tablePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(summaryLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalCaloriesLbl)
                .addGap(18, 18, 18)
                .addComponent(macrosLbl)
                .addGap(37, 37, 37)
                .addComponent(backBtn)
                .addGap(49, 49, 49))
        );

        mainPagePnl.setBackground(new java.awt.Color(210, 244, 234));
        mainPagePnl.setForeground(new java.awt.Color(255, 255, 255));
        mainPagePnl.setPreferredSize(new java.awt.Dimension(425, 371));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 5));
        titleLbl.setText("Diet Tracker");

        addMealBtn.setBackground(new java.awt.Color(142, 218, 114));
        addMealBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addMealBtn.setForeground(new java.awt.Color(0, 102, 51));
        addMealBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dietapp/images/addBtn.png"))); // NOI18N
        addMealBtn.setText("Add Meal");
        addMealBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        addMealBtn.setBorderPainted(false);
        addMealBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMealBtn.setPreferredSize(new java.awt.Dimension(110, 23));
        addMealBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addMealBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addMealBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealBtnActionPerformed(evt);
            }
        });

        viewSummaryBtn.setBackground(new java.awt.Color(142, 218, 114));
        viewSummaryBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewSummaryBtn.setForeground(new java.awt.Color(0, 102, 51));
        viewSummaryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dietapp/images/viewBtn.png"))); // NOI18N
        viewSummaryBtn.setText("View Summary");
        viewSummaryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        viewSummaryBtn.setBorderPainted(false);
        viewSummaryBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewSummaryBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        viewSummaryBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewSummaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSummaryBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 46), 2, true));
        mainMenuBtn.setBorderPainted(false);
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        sentenceLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        sentenceLbl.setForeground(new java.awt.Color(51, 51, 51));
        sentenceLbl.setText("Keep track of all your meals!");

        javax.swing.GroupLayout mainPagePnlLayout = new javax.swing.GroupLayout(mainPagePnl);
        mainPagePnl.setLayout(mainPagePnlLayout);
        mainPagePnlLayout.setHorizontalGroup(
            mainPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPagePnlLayout.createSequentialGroup()
                .addGroup(mainPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPagePnlLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(titleLbl))
                    .addGroup(mainPagePnlLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(sentenceLbl))
                    .addGroup(mainPagePnlLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(addMealBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewSummaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPagePnlLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mainPagePnlLayout.setVerticalGroup(
            mainPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPagePnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sentenceLbl)
                .addGap(46, 46, 46)
                .addGroup(mainPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMealBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewSummaryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mealEntryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tablePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPagePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mealEntryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tablePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPagePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mealTypeCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealTypeCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealTypeCmbActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainPagePnl.setVisible(true);
        mealEntryPnl.setVisible(false);
        tablePnl.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addMealBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealBtnActionPerformed
        // TODO add your handling code here:
        mainPagePnl.setVisible(false);
        mealEntryPnl.setVisible(true);
        tablePnl.setVisible(false);
        
    }//GEN-LAST:event_addMealBtnActionPerformed

    private void viewSummaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSummaryBtnActionPerformed
        // TODO add your handling code here:
        mainPagePnl.setVisible(false);
        mealEntryPnl.setVisible(false);
        tablePnl.setVisible(true);
    }//GEN-LAST:event_viewSummaryBtnActionPerformed

    private void back1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1BtnActionPerformed
        // TODO add your handling code here:
        mainPagePnl.setVisible(true);
        mealEntryPnl.setVisible(false);
        tablePnl.setVisible(false);
    }//GEN-LAST:event_back1BtnActionPerformed

    private void summaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBtnActionPerformed
        // TODO add your handling code here:
        mainPagePnl.setVisible(false);
        mealEntryPnl.setVisible(false);
        tablePnl.setVisible(true);
    }//GEN-LAST:event_summaryBtnActionPerformed

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        // TODO add your handling code here:
        mainmenu.MainMenuGUI mainMenu= new mainmenu.MainMenuGUI();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DietGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addMealBtn;
    private javax.swing.JButton back1Btn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel caloriesLbl;
    private javax.swing.JTextField caloriesTF;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel dietTrackerLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel macrosLbl;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JPanel mainPagePnl;
    private javax.swing.JPanel mealEntryPnl;
    private javax.swing.JTable mealEntryTbl;
    private javax.swing.JLabel mealNameLbl;
    private javax.swing.JTextField mealNameTF;
    private javax.swing.JComboBox<String> mealTypeCmb;
    private javax.swing.JLabel mealTypeLbl;
    private javax.swing.JLabel sentenceLbl;
    private javax.swing.JButton summaryBtn;
    private javax.swing.JLabel summaryLbl;
    private javax.swing.JPanel tablePnl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel totalCaloriesLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewSummaryBtn;
    // End of variables declaration//GEN-END:variables
}
