/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainmenu;

import exerciseapp.ExerciseGUI;
import dietapp.DietGUI;
import sleepapp.SleepGUI;

/**
 *
 * @author dhruva
 */
public class MainMenuGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuGUI.class.getName());
    private ExerciseGUI exercise;
    private DietGUI diet;
    private SleepGUI sleep;

    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
        exercise = new ExerciseGUI();
        diet= new DietGUI();
        sleep= new SleepGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        subTitleLbl = new javax.swing.JLabel();
        dietBtn = new javax.swing.JButton();
        exerciseBtn = new javax.swing.JButton();
        sleepBtn = new javax.swing.JButton();
        footorLbl = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPnl.setBackground(new java.awt.Color(210, 244, 234));
        mainPnl.setForeground(new java.awt.Color(255, 255, 255));
        mainPnl.setPreferredSize(new java.awt.Dimension(430, 380));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 51));
        titleLbl.setText("Healthy Life App");

        subTitleLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        subTitleLbl.setForeground(new java.awt.Color(51, 51, 51));
        subTitleLbl.setText("Your daily wellness companion");

        dietBtn.setBackground(new java.awt.Color(142, 218, 114));
        dietBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dietBtn.setForeground(new java.awt.Color(0, 102, 51));
        dietBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainmenu/images/diet.png"))); // NOI18N
        dietBtn.setText("Diet Tracker");
        dietBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dietBtn.setBorderPainted(false);
        dietBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dietBtn.setIconTextGap(15);
        dietBtn.setMaximumSize(new java.awt.Dimension(95, 23));
        dietBtn.setMinimumSize(new java.awt.Dimension(95, 23));
        dietBtn.setPreferredSize(new java.awt.Dimension(95, 23));
        dietBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dietBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dietBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietBtnActionPerformed(evt);
            }
        });

        exerciseBtn.setBackground(new java.awt.Color(142, 218, 114));
        exerciseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exerciseBtn.setForeground(new java.awt.Color(0, 102, 51));
        exerciseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainmenu/images/exercise.png"))); // NOI18N
        exerciseBtn.setText("Exercise Tracker");
        exerciseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 1, true));
        exerciseBtn.setBorderPainted(false);
        exerciseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exerciseBtn.setIconTextGap(15);
        exerciseBtn.setMaximumSize(new java.awt.Dimension(95, 23));
        exerciseBtn.setMinimumSize(new java.awt.Dimension(95, 23));
        exerciseBtn.setPreferredSize(new java.awt.Dimension(95, 23));
        exerciseBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        exerciseBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exerciseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exerciseBtnActionPerformed(evt);
            }
        });

        sleepBtn.setBackground(new java.awt.Color(142, 218, 114));
        sleepBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sleepBtn.setForeground(new java.awt.Color(0, 102, 51));
        sleepBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainmenu/images/sleep.png"))); // NOI18N
        sleepBtn.setText("Sleep Tracker");
        sleepBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sleepBtn.setBorderPainted(false);
        sleepBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sleepBtn.setIconTextGap(15);
        sleepBtn.setMaximumSize(new java.awt.Dimension(95, 23));
        sleepBtn.setMinimumSize(new java.awt.Dimension(95, 23));
        sleepBtn.setPreferredSize(new java.awt.Dimension(95, 23));
        sleepBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sleepBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sleepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepBtnActionPerformed(evt);
            }
        });

        footorLbl.setForeground(new java.awt.Color(51, 51, 51));
        footorLbl.setText("@2025 Good Health and Well-being | Team P");

        javax.swing.GroupLayout mainPnlLayout = new javax.swing.GroupLayout(mainPnl);
        mainPnl.setLayout(mainPnlLayout);
        mainPnlLayout.setHorizontalGroup(
            mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnlLayout.createSequentialGroup()
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPnlLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(dietBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(exerciseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(sleepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLbl))
                    .addGroup(mainPnlLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(subTitleLbl)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(footorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        mainPnlLayout.setVerticalGroup(
            mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sleepBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(dietBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exerciseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(footorLbl)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dietBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietBtnActionPerformed
        // TODO add your handling code here:
        dietapp.DietGUI dietWindow = new dietapp.DietGUI();
        dietWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dietBtnActionPerformed

    private void exerciseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerciseBtnActionPerformed
        // TODO add your handling code here:
        exerciseapp.ExerciseGUI exerciseWindow = new exerciseapp.ExerciseGUI();
        exerciseWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exerciseBtnActionPerformed

    private void sleepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepBtnActionPerformed
        // TODO add your handling code here:
        sleepapp.SleepGUI sleepWindow = new SleepGUI();
        sleepWindow.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_sleepBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MainMenuGUI myMenu = new MainMenuGUI();
        myMenu.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dietBtn;
    private javax.swing.JButton exerciseBtn;
    private javax.swing.JLabel footorLbl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JButton sleepBtn;
    private javax.swing.JLabel subTitleLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
