/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sleepapp;
import javax.swing.table.DefaultTableModel;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;


import java.time.LocalTime; //Allows us to control and update table data
import java.time.Duration; //Used for calculating time differences (sleep duration)

/**
 *
 * @author Mridhula Vijayakumar
 */
public class SleepGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SleepGUI.class.getName());
    // Create an object of SleepManager to store all sleep records
    private final SleepManager s = new SleepManager();
    
    // Arrays storing helpful sleep tips depending on sleep quality
    private final String[] goodTips = {
        "Awesome sleeper! Keep maintaining a consistent routine",
    "Great job! Your body loves this recovery.",
    "Keep it up! Quality sleep = better health and focus",
    "You are giving your brain the rest it deserves",
    "Your immune system says THANK YOU!",
    "Great rhythm! Keep the same sleep schedule daily",
    "Your productivity and mood benefit from this",
    "Stay consistent! You're winning at sleep"
    };

    private final String[] averageTips = {
        "You're close! Try to sleep 30–60 minutes earlier for full recovery.",
    "Good effort! Improve bedtime regularity for better sleep",
    "A little earlier sleep could improve your energy",
    "Keep screens away 30 minutes before bedtime",
    "Consider using dim lights before sleeping️",
    "A cozy blanket and cool room improve sleep quality️",
    "Light exercise in the evening can help you fall asleep faster️",
    "Stay hydrated during the day, but avoid too much water before sleep"
    };

    private final String[] poorTips = {
        "Sleep more! Aim for at least 7–8 hours daily",
    "Try reducing screen time before bed",
    "Avoid caffeine past 6PM for better sleep",
    "Create a calm, dark bedroom environment",
    "Try going to bed and waking up at the same time every day",
    "Reduce late-night heavy meals️",
    "Short naps are okay, but avoid long naps late in the day",
    "Try relaxing techniques: meditation or warm bath before bed"
    };
    
    /**
     * Creates new form SleepGUI
     */
    
    // Contructor
    public SleepGUI() {
        initComponents();
        // Hide all sub-panels at first — only main buttons are visible
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);
        viewAvgSleepField.setEditable(false);
        
        // Whenever the summary bar is resized, update its display properly
        viewColorBarPnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                updateSummary();
                // Recalculates and redraws health color bar
            }
        });

        loadTableData(); // Load saved data from file into table
        updateSummary(); // Load saved summary when app opens


        // Default placeholder text
        addDateField.setText("DD-MM-YYYY");
        
        // Time spinners formatted to show hours and minutes
        addSleepTSpinner.setEditor(new javax.swing.JSpinner.DateEditor(addSleepTSpinner, "HH:mm"));
        addWakeTSpinner.setEditor(new javax.swing.JSpinner.DateEditor(addWakeTSpinner, "HH:mm"));


        // When user clicks into date field — clear placeholder
        addDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (addDateField.getText().equals("DD-MM-YYYY"))
                    addDateField.setText("");
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (addDateField.getText().isEmpty())
                    addDateField.setText("DD-MM-YYYY");
            }
        });

        // Duration is always automatically calculated, not typed
        addDurationField.setEditable(false);
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSleepPnl = new javax.swing.JPanel();
        mainTitleLbl = new javax.swing.JLabel();
        mainSubTitleLbl = new javax.swing.JLabel();
        mainAddSleepBtn = new javax.swing.JButton();
        mainViewSumBtn = new javax.swing.JButton();
        mainBackBtn = new javax.swing.JButton();
        addSleepPnl = new javax.swing.JPanel();
        addSleepTitleLbl = new javax.swing.JLabel();
        addDateLbl = new javax.swing.JLabel();
        addSleepTimeLbl = new javax.swing.JLabel();
        addWakeTimeLbl = new javax.swing.JLabel();
        addDurationLbl = new javax.swing.JLabel();
        addDateField = new javax.swing.JTextField();
        addDurationField = new javax.swing.JTextField();
        addSaveBtn = new javax.swing.JButton();
        addBackBtn = new javax.swing.JButton();
        addClearBtn = new javax.swing.JButton();
        addDisplayBtn = new javax.swing.JButton();
        addSleepTSpinner = new javax.swing.JSpinner();
        addWakeTSpinner = new javax.swing.JSpinner();
        viewSleepPnl = new javax.swing.JPanel();
        viewSumLbl = new javax.swing.JLabel();
        viewSleepTablePnl = new javax.swing.JPanel();
        viewSleepTableScrollP = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        sleepTbl = new javax.swing.JTable();
        viewSleepSumPnl = new javax.swing.JPanel();
        viewAvgSleepLbl = new javax.swing.JLabel();
        viewAvgSleepField = new javax.swing.JTextField();
        viewSleepHealthLbl = new javax.swing.JLabel();
        viewColorBarPnl = new javax.swing.JPanel();
        viewTipBtn = new javax.swing.JButton();
        viewBackBtn = new javax.swing.JButton();
        showTipPnl = new javax.swing.JPanel();
        showTipTitleLbl = new javax.swing.JLabel();
        showTipScrollP = new javax.swing.JScrollPane();
        showTipArea = new javax.swing.JTextArea();
        showAnotherTipBtn = new javax.swing.JButton();
        showBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 371));

        mainSleepPnl.setBackground(new java.awt.Color(210, 244, 234));
        mainSleepPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        mainSleepPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        mainSleepPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainTitleLbl.setForeground(new java.awt.Color(0, 102, 0));
        mainTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/night.png"))); // NOI18N
        mainTitleLbl.setText("Sleep Tracker");
        mainSleepPnl.add(mainTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, 70));

        mainSubTitleLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        mainSubTitleLbl.setForeground(new java.awt.Color(64, 64, 64));
        mainSubTitleLbl.setText("Monitor and improve your sleep");
        mainSleepPnl.add(mainSubTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, 20));

        mainAddSleepBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainAddSleepBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mainAddSleepBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainAddSleepBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/sleep.png"))); // NOI18N
        mainAddSleepBtn.setText("Add Sleep Session");
        mainAddSleepBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        mainAddSleepBtn.setBorderPainted(false);
        mainAddSleepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainAddSleepBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainAddSleepBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainAddSleepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddSleepBtnActionPerformed(evt);
            }
        });
        mainSleepPnl.add(mainAddSleepBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 100));

        mainViewSumBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainViewSumBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mainViewSumBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainViewSumBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/graph.png"))); // NOI18N
        mainViewSumBtn.setText("View Summary");
        mainViewSumBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        mainViewSumBtn.setBorderPainted(false);
        mainViewSumBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainViewSumBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainViewSumBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainViewSumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainViewSumBtnActionPerformed(evt);
            }
        });
        mainSleepPnl.add(mainViewSumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, 100));

        mainBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainBackBtn.setText("Main Menu");
        mainBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        mainBackBtn.setBorderPainted(false);
        mainBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBackBtnActionPerformed(evt);
            }
        });
        mainSleepPnl.add(mainBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 30));

        addSleepPnl.setBackground(new java.awt.Color(210, 244, 234));
        addSleepPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addSleepPnl.setForeground(new java.awt.Color(0, 102, 51));
        addSleepPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        addSleepPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        addSleepPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSleepTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addSleepTitleLbl.setForeground(new java.awt.Color(0, 102, 0));
        addSleepTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/sleep.png"))); // NOI18N
        addSleepTitleLbl.setText("Sleep Tracker");
        addSleepPnl.add(addSleepTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        addDateLbl.setBackground(new java.awt.Color(204, 204, 255));
        addDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/calendar.png"))); // NOI18N
        addDateLbl.setText("DATE: ");
        addSleepPnl.add(addDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, -1));

        addSleepTimeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSleepTimeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/enoughsleep.png"))); // NOI18N
        addSleepTimeLbl.setText("Sleep Time: ");
        addSleepTimeLbl.setMaximumSize(new java.awt.Dimension(84, 25));
        addSleepTimeLbl.setMinimumSize(new java.awt.Dimension(84, 25));
        addSleepTimeLbl.setPreferredSize(new java.awt.Dimension(84, 25));
        addSleepPnl.add(addSleepTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, -1));

        addWakeTimeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addWakeTimeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/wakeup.png"))); // NOI18N
        addWakeTimeLbl.setText("Wake Time:");
        addWakeTimeLbl.setMaximumSize(new java.awt.Dimension(84, 25));
        addWakeTimeLbl.setMinimumSize(new java.awt.Dimension(84, 25));
        addWakeTimeLbl.setPreferredSize(new java.awt.Dimension(84, 25));
        addSleepPnl.add(addWakeTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        addDurationLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDurationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/hourglass.png"))); // NOI18N
        addDurationLbl.setText("Duration (Hrs): ");
        addDurationLbl.setMaximumSize(new java.awt.Dimension(84, 25));
        addDurationLbl.setMinimumSize(new java.awt.Dimension(84, 25));
        addDurationLbl.setPreferredSize(new java.awt.Dimension(84, 25));
        addSleepPnl.add(addDurationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, -1));

        addDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateFieldActionPerformed(evt);
            }
        });
        addSleepPnl.add(addDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, -1));

        addDurationField.setEnabled(false);
        addSleepPnl.add(addDurationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, -1));

        addSaveBtn.setBackground(new java.awt.Color(142, 218, 114));
        addSaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSaveBtn.setForeground(new java.awt.Color(0, 102, 51));
        addSaveBtn.setText("Ok / Save");
        addSaveBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        addSaveBtn.setBorderPainted(false);
        addSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSaveBtnActionPerformed(evt);
            }
        });
        addSleepPnl.add(addSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 30));

        addBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        addBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        addBackBtn.setText("Back");
        addBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        addBackBtn.setBorderPainted(false);
        addBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBackBtnActionPerformed(evt);
            }
        });
        addSleepPnl.add(addBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 30));

        addClearBtn.setBackground(new java.awt.Color(142, 218, 114));
        addClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addClearBtn.setForeground(new java.awt.Color(0, 102, 51));
        addClearBtn.setText("Clear");
        addClearBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addClearBtn.setBorderPainted(false);
        addClearBtn.setMaximumSize(new java.awt.Dimension(35, 24));
        addClearBtn.setMinimumSize(new java.awt.Dimension(35, 24));
        addClearBtn.setPreferredSize(new java.awt.Dimension(35, 24));
        addClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClearBtnActionPerformed(evt);
            }
        });
        addSleepPnl.add(addClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 80, 30));

        addDisplayBtn.setBackground(new java.awt.Color(142, 218, 114));
        addDisplayBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDisplayBtn.setForeground(new java.awt.Color(0, 102, 51));
        addDisplayBtn.setText("Display");
        addDisplayBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addDisplayBtn.setBorderPainted(false);
        addDisplayBtn.setMaximumSize(new java.awt.Dimension(35, 24));
        addDisplayBtn.setMinimumSize(new java.awt.Dimension(35, 24));
        addDisplayBtn.setPreferredSize(new java.awt.Dimension(35, 24));
        addDisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisplayBtnActionPerformed(evt);
            }
        });
        addSleepPnl.add(addDisplayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 80, 30));

        addSleepTSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        addSleepPnl.add(addSleepTSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, -1));

        addWakeTSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        addSleepPnl.add(addWakeTSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));

        viewSleepPnl.setBackground(new java.awt.Color(210, 244, 234));
        viewSleepPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        viewSleepPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        viewSleepPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewSumLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewSumLbl.setForeground(new java.awt.Color(0, 102, 0));
        viewSumLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/dashboard.png"))); // NOI18N
        viewSumLbl.setText("Sleep Summary");
        viewSleepPnl.add(viewSumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, -1));

        viewSleepTablePnl.setLayout(new java.awt.BorderLayout());

        sleepTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Sleep Time", "Wake Time", "Duration"
            }
        ));
        jScrollPane1.setViewportView(sleepTbl);

        viewSleepTableScrollP.setViewportView(jScrollPane1);

        viewSleepTablePnl.add(viewSleepTableScrollP, java.awt.BorderLayout.CENTER);

        viewSleepPnl.add(viewSleepTablePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 130));

        viewSleepSumPnl.setBackground(new java.awt.Color(255, 255, 255));

        viewAvgSleepLbl.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        viewAvgSleepLbl.setText("Average Sleep (Hrs): ");

        viewAvgSleepField.setBorder(null);
        viewAvgSleepField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvgSleepFieldActionPerformed(evt);
            }
        });

        viewSleepHealthLbl.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        viewSleepHealthLbl.setText("Sleep Health: ");

        viewColorBarPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout viewColorBarPnlLayout = new javax.swing.GroupLayout(viewColorBarPnl);
        viewColorBarPnl.setLayout(viewColorBarPnlLayout);
        viewColorBarPnlLayout.setHorizontalGroup(
            viewColorBarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        viewColorBarPnlLayout.setVerticalGroup(
            viewColorBarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viewSleepSumPnlLayout = new javax.swing.GroupLayout(viewSleepSumPnl);
        viewSleepSumPnl.setLayout(viewSleepSumPnlLayout);
        viewSleepSumPnlLayout.setHorizontalGroup(
            viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                .addGroup(viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                        .addComponent(viewAvgSleepLbl)
                        .addGap(18, 18, 18)
                        .addComponent(viewAvgSleepField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(viewColorBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewSleepHealthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewSleepSumPnlLayout.setVerticalGroup(
            viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAvgSleepLbl)
                    .addComponent(viewAvgSleepField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewSleepHealthLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewColorBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        viewSleepPnl.add(viewSleepSumPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 400, 90));

        viewTipBtn.setBackground(new java.awt.Color(142, 218, 114));
        viewTipBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewTipBtn.setForeground(new java.awt.Color(0, 102, 51));
        viewTipBtn.setText("Sleep Tip");
        viewTipBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        viewTipBtn.setBorderPainted(false);
        viewTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTipBtnActionPerformed(evt);
            }
        });
        viewSleepPnl.add(viewTipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 110, -1));

        viewBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        viewBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        viewBackBtn.setText("Back");
        viewBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        viewBackBtn.setBorderPainted(false);
        viewBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBackBtnActionPerformed(evt);
            }
        });
        viewSleepPnl.add(viewBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, -1));

        showTipPnl.setBackground(new java.awt.Color(210, 244, 234));
        showTipPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        showTipPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        showTipPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showTipTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        showTipTitleLbl.setForeground(new java.awt.Color(0, 102, 0));
        showTipTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/lamp.png"))); // NOI18N
        showTipTitleLbl.setText("Sleep Tip");
        showTipPnl.add(showTipTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, 50));

        showTipArea.setEditable(false);
        showTipArea.setColumns(20);
        showTipArea.setLineWrap(true);
        showTipArea.setRows(5);
        showTipArea.setWrapStyleWord(true);
        showTipScrollP.setViewportView(showTipArea);

        showTipPnl.add(showTipScrollP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, 100));

        showAnotherTipBtn.setBackground(new java.awt.Color(142, 218, 114));
        showAnotherTipBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showAnotherTipBtn.setForeground(new java.awt.Color(0, 102, 51));
        showAnotherTipBtn.setText("Show Another Tip");
        showAnotherTipBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        showAnotherTipBtn.setBorderPainted(false);
        showAnotherTipBtn.setMaximumSize(new java.awt.Dimension(156, 24));
        showAnotherTipBtn.setMinimumSize(new java.awt.Dimension(156, 24));
        showAnotherTipBtn.setPreferredSize(new java.awt.Dimension(156, 24));
        showAnotherTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAnotherTipBtnActionPerformed(evt);
            }
        });
        showTipPnl.add(showAnotherTipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 30));

        showBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        showBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        showBackBtn.setText("Back");
        showBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        showBackBtn.setBorderPainted(false);
        showBackBtn.setMaximumSize(new java.awt.Dimension(35, 24));
        showBackBtn.setMinimumSize(new java.awt.Dimension(35, 24));
        showBackBtn.setPreferredSize(new java.awt.Dimension(35, 24));
        showBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBackBtnActionPerformed(evt);
            }
        });
        showTipPnl.add(showBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(showTipPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewSleepPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(showTipPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainViewSumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainViewSumBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(false);// Hide the main panel
        viewSleepPnl.setVisible(true);// Show the summary panel
        loadTableData();// Load all saved sleep records into the table
        updateSummary();// Refresh average sleep + color bar display

    }//GEN-LAST:event_mainViewSumBtnActionPerformed

    private void addDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDateFieldActionPerformed

    private void mainAddSleepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddSleepBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(false);// Hide main page
        addSleepPnl.setVisible(true);// Show Add Sleep page

    }//GEN-LAST:event_mainAddSleepBtnActionPerformed

    private void viewBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBackBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(true);// Show main menu
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);
    }//GEN-LAST:event_viewBackBtnActionPerformed

    private void addBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBackBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(true);
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);

    }//GEN-LAST:event_addBackBtnActionPerformed

    private void showBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBackBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(true);
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);
    }//GEN-LAST:event_showBackBtnActionPerformed

    private void viewTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTipBtnActionPerformed
        // TODO add your handling code here:
        viewSleepPnl.setVisible(false);// Hide summary page
        showTipPnl.setVisible(true);// Show the tip page
        
        showTip(); // Display a random sleep tip instantly

    }//GEN-LAST:event_viewTipBtnActionPerformed

    private void mainBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBackBtnActionPerformed
        // TODO add your handling code here:
        mainmenu.MainMenuGUI mainMenu= new mainmenu.MainMenuGUI();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainBackBtnActionPerformed

    private void addClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClearBtnActionPerformed
        // TODO add your handling code here:
        addDateField.setText("DD-MM-YYYY");// Reset input field
        addDurationField.setText("");
        // Clear auto-calculated duration display
        
        // Reset sleep & wake spinners to current time
        addSleepTSpinner.setValue(new java.util.Date());
        addWakeTSpinner.setValue(new java.util.Date());
        
    }//GEN-LAST:event_addClearBtnActionPerformed
    
    
    
    private void addDisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisplayBtnActionPerformed
        // TODO add your handling code here:
        addSleepPnl.setVisible(false);      // hide Add panel
        viewSleepPnl.setVisible(true);   // show Summary panel
        
        loadTableData(); // Refresh table data
        updateSummary(); // Refresh average + sleep health bar
        
   
    }//GEN-LAST:event_addDisplayBtnActionPerformed
    // This method updates the Sleep Summary section:
    private void updateSummary() {

        double avg = s.getAverageHours(); // Get the average sleep duration stored in SleepManager
        
        // If panel height is too small, increase it so bar is visible
        if (viewColorBarPnl.getHeight() < 20) {
            viewColorBarPnl.setPreferredSize(new java.awt.Dimension(
                viewColorBarPnl.getWidth(), 25));
        }

        // Display the average hours in the text field (formatted to 2 decimal places)
        viewAvgSleepField.setText(String.format("%.2f", avg));

        // Convert average hours into a percentage (8 hours = 100%)
        int percent = (int)((avg / 8.0) * 100);
        
        // Make sure the percentage stays between 0% and 100%
        percent = Math.max(0, Math.min(percent, 100));
        
        // Select color for the sleep health bar based on sleep quality
        java.awt.Color barColor;
        if (avg < 6) {
            barColor = java.awt.Color.RED; // Less than 6 hrs = Poor sleep
        } else if (avg < 8) {
            barColor = java.awt.Color.YELLOW; // 6–7.9 hrs = Average sleep
        } else {
            barColor = java.awt.Color.GREEN; // 8+ hrs = Good sleep
        }


        // Create a new small panel that will act as the colored bar
        javax.swing.JPanel bar = new javax.swing.JPanel();
        bar.setBackground(barColor);// Give it the right color

        viewColorBarPnl.setLayout(null); // Remove auto-layout so we can manually size the bar

        int totalWidth = viewColorBarPnl.getWidth();
        if (totalWidth == 0) totalWidth = 300;
        // If width not loaded yet, use a temporary width
        // Width of bar depends on percentage (example: 75% = 75% width)
        int barWidth = (int)(totalWidth * (percent / 100.0));

        // Make bar height same as panel height or minimum height 25px
        int barHeight = Math.max(viewColorBarPnl.getHeight(), 25);
        bar.setBounds(0, 0, barWidth, barHeight);// Position and size the bar
        viewColorBarPnl.add(bar);// Add bar to panel

        // Create %, shown as text over the bar
        javax.swing.JLabel txt = new javax.swing.JLabel(percent + "%", javax.swing.SwingConstants.CENTER);
        txt.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        txt.setForeground(java.awt.Color.BLACK);// Black text for visibility
        txt.setBounds(0, 0, totalWidth, barHeight);// Same size as whole panel
        viewColorBarPnl.add(txt);// Add label on top of bar
        
        // Refresh the panel so changes show immediately
        viewColorBarPnl.revalidate();
        viewColorBarPnl.repaint();

    }
    // This method shows a new sleep tip based on the user’s average sleep quality
    private void showTip() {
        double avg = s.getAverageHours();
        // Get the average hours to choose correct tip category
        java.util.Random rand = new java.util.Random(); // Random generator to pick a different tip each time
        String tip; // Store the final selected tip
        
        // Choose a tip group based on sleep health
        if (avg < 6) {
            tip = poorTips[rand.nextInt(poorTips.length)];// Poor sleep - pick from poor tips list
        } else if (avg < 8) {
            tip = averageTips[rand.nextInt(averageTips.length)];// Average sleep - pick from average tips list
        } else {
            tip = goodTips[rand.nextInt(goodTips.length)];// Good sleep - pick from good tips list
        }
        
        // Display the selected tip inside the scrollable text area
        showTipArea.setText("Sleep Tip:\n\n" + tip);
        // add header + tip text with spacing
    }



    
    private void addSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSaveBtnActionPerformed
        // TODO add your handling code here:
        // Read user input
        // Read the text entered in the Date field (remove extra spaces)
        String date = addDateField.getText().trim();

        // Validate Date Field
        if (date.isEmpty() || date.equals("DD-MM-YYYY")) {
            // Show popup if date field is blank or still in placeholder form
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter a valid date!",
                "Input Error",
                javax.swing.JOptionPane.PLAIN_MESSAGE);

            return;// Stop further execution
        }

        // Validate Date Format (DD-MM-YYYY)
        if (!date.matches("\\d{2}-\\d{2}-\\d{4}")) {
            // If the date does not match the correct pattern - show error
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter a valid date!",
                "Input Error",
                javax.swing.JOptionPane.PLAIN_MESSAGE);

            return;
        }
        // Formatter to convert time from spinner into HH:mm (24-hour format)
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm");
        sdf.setLenient(false);// Strict checking for time format
        
        // Convert selected spinner times into text form (e.g. "00:00")
        String sleepT = sdf.format(addSleepTSpinner.getValue());
        String wakeT = sdf.format(addWakeTSpinner.getValue());

        // Extract sleep time hour & minute from spinners
        java.util.Calendar cal1 = java.util.Calendar.getInstance();
        cal1.setTime((java.util.Date) addSleepTSpinner.getValue());
        int sh = cal1.get(java.util.Calendar.HOUR_OF_DAY);// sleep hour
        int sm = cal1.get(java.util.Calendar.MINUTE);// sleep minute
        
        // Extract wake time hour+minute values from spinner
        java.util.Calendar cal2 = java.util.Calendar.getInstance();
        cal2.setTime((java.util.Date) addWakeTSpinner.getValue());
        int wh = cal2.get(java.util.Calendar.HOUR_OF_DAY);// wake hour
        int wm = cal2.get(java.util.Calendar.MINUTE);// wake minute
        
        // Convert both times into total minutes from midnight
        int startTotal = sh * 60 + sm;
        int wakeTotal = wh * 60 + wm;

        // Overnight case handling
        if (wakeTotal < startTotal) {
            wakeTotal += 24 * 60;// Add 24 hours to calculate correct duration
        }
        
        // Calculate duration in minutes
        int durationMins = wakeTotal - startTotal;

        // Validate Duration
        if (durationMins <= 0) {
            // Invalid Duartion
            javax.swing.JOptionPane.showMessageDialog(this,
                "Wake time must be later than sleep time!",
                "Time Error",
                javax.swing.JOptionPane.PLAIN_MESSAGE);
            return;
        }
        
        // Convert minutes into a decimal hours value
        double duration = durationMins / 60.0;
        
        // Split duration into hours and minutes for pretty display
        int hours = durationMins / 60;
        int mins = durationMins % 60;
        
        // Format duration result like “06:30”
        String durationStr = String.format("%02d:%02d", hours, mins);
        
        //Display duration in the duration textbox
        addDurationField.setText(durationStr);

        // Save to system
        SleepApp entry = new SleepApp(date, sleepT, wakeT, duration);
        // Store the new entry in memory (ArrayList) and in text file
        s.addEntry(entry);
        s.saveToFile();
        
        // Update table so user instantly sees added record
        loadTableData();
        
        //final message dialog
        javax.swing.JOptionPane.showMessageDialog(this,
            "Saved successfully!");
    }//GEN-LAST:event_addSaveBtnActionPerformed

    private void viewAvgSleepFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvgSleepFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAvgSleepFieldActionPerformed

    private void showAnotherTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAnotherTipBtnActionPerformed
        // TODO add your handling code here:
        showTip();
    }//GEN-LAST:event_showAnotherTipBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SleepGUI().setVisible(true));
    }
    
    // Load all stored sleep data into JTable
    public void loadTableData() {
    DefaultTableModel model = (DefaultTableModel) sleepTbl.getModel();
    model.setRowCount(0);// Clear previous rows

    // Add each record from SleepManager into table row
    for (SleepApp e : s.getEntries()) {
        model.addRow(new Object[]{
            e.getDate(),
            e.getSleepTime(),
            e.getWakeTime(),
            e.getDurationInHHMM() //formatted duration
        });
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBackBtn;
    private javax.swing.JButton addClearBtn;
    private javax.swing.JTextField addDateField;
    private javax.swing.JLabel addDateLbl;
    private javax.swing.JButton addDisplayBtn;
    private javax.swing.JTextField addDurationField;
    private javax.swing.JLabel addDurationLbl;
    private javax.swing.JButton addSaveBtn;
    private javax.swing.JPanel addSleepPnl;
    private javax.swing.JSpinner addSleepTSpinner;
    private javax.swing.JLabel addSleepTimeLbl;
    private javax.swing.JLabel addSleepTitleLbl;
    private javax.swing.JSpinner addWakeTSpinner;
    private javax.swing.JLabel addWakeTimeLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainAddSleepBtn;
    private javax.swing.JButton mainBackBtn;
    private javax.swing.JPanel mainSleepPnl;
    private javax.swing.JLabel mainSubTitleLbl;
    private javax.swing.JLabel mainTitleLbl;
    private javax.swing.JButton mainViewSumBtn;
    private javax.swing.JButton showAnotherTipBtn;
    private javax.swing.JButton showBackBtn;
    private javax.swing.JTextArea showTipArea;
    private javax.swing.JPanel showTipPnl;
    private javax.swing.JScrollPane showTipScrollP;
    private javax.swing.JLabel showTipTitleLbl;
    private javax.swing.JTable sleepTbl;
    private javax.swing.JTextField viewAvgSleepField;
    private javax.swing.JLabel viewAvgSleepLbl;
    private javax.swing.JButton viewBackBtn;
    private javax.swing.JPanel viewColorBarPnl;
    private javax.swing.JLabel viewSleepHealthLbl;
    private javax.swing.JPanel viewSleepPnl;
    private javax.swing.JPanel viewSleepSumPnl;
    private javax.swing.JPanel viewSleepTablePnl;
    private javax.swing.JScrollPane viewSleepTableScrollP;
    private javax.swing.JLabel viewSumLbl;
    private javax.swing.JButton viewTipBtn;
    // End of variables declaration//GEN-END:variables
}
