/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sleepapp;

/**
 *
 * @author Mridhula Vijayakumar
 */
public class SleepGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SleepGUI.class.getName());

    /**
     * Creates new form SleepGUI
     */
    public SleepGUI() {
        initComponents();
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSleepPnl = new javax.swing.JPanel();
        mainTitleLbl = new javax.swing.JLabel();
        mainSubTitleLbl = new javax.swing.JLabel();
        mainAddSleepBtn = new javax.swing.JButton();
        mainViewSumBtn = new javax.swing.JButton();
        mainBackBtn = new javax.swing.JButton();
        addSleepPnl = new javax.swing.JPanel();
        addSleepTitleLbl = new javax.swing.JLabel();
        addDateLbl = new javax.swing.JLabel();
        addSleepTimeLbl = new javax.swing.JLabel();
        addWakeTimeLbl = new javax.swing.JLabel();
        addDurationLbl = new javax.swing.JLabel();
        addDateField = new javax.swing.JTextField();
        addSleepTimeField = new javax.swing.JTextField();
        addWakeTimeField = new javax.swing.JTextField();
        addDurationField = new javax.swing.JTextField();
        addSaveBtn = new javax.swing.JButton();
        addBackBtn = new javax.swing.JButton();
        viewSleepPnl = new javax.swing.JPanel();
        viewSumLbl = new javax.swing.JLabel();
        viewSleepTablePnl = new javax.swing.JPanel();
        viewSleepTableScrollP = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        sleepTbl = new javax.swing.JTable();
        viewSleepSumPnl = new javax.swing.JPanel();
        viewAvgSleepLbl = new javax.swing.JLabel();
        viewAvgSleepField = new javax.swing.JTextField();
        viewSleepHealthLbl = new javax.swing.JLabel();
        viewColorBarPnl = new javax.swing.JPanel();
        viewTipBtn = new javax.swing.JButton();
        viewBackBtn = new javax.swing.JButton();
        showTipPnl = new javax.swing.JPanel();
        showTipTitleLbl = new javax.swing.JLabel();
        showTipScrollP = new javax.swing.JScrollPane();
        showTipArea = new javax.swing.JTextArea();
        showAnotherTipBtn = new javax.swing.JButton();
        showBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 371));

        mainSleepPnl.setBackground(new java.awt.Color(210, 244, 234));
        mainSleepPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        mainSleepPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        mainSleepPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainTitleLbl.setForeground(new java.awt.Color(0, 102, 0));
        mainTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/night.png"))); // NOI18N
        mainTitleLbl.setText("Sleep Tracker");
        mainSleepPnl.add(mainTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, 70));

        mainSubTitleLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        mainSubTitleLbl.setForeground(new java.awt.Color(64, 64, 64));
        mainSubTitleLbl.setText("Monitor and improve your sleep");
        mainSleepPnl.add(mainSubTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, 20));

        mainAddSleepBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainAddSleepBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mainAddSleepBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainAddSleepBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/sleep.png"))); // NOI18N
        mainAddSleepBtn.setText("Add Sleep Session");
        mainAddSleepBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        mainAddSleepBtn.setBorderPainted(false);
        mainAddSleepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainAddSleepBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainAddSleepBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainAddSleepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddSleepBtnActionPerformed(evt);
            }
        });
        mainSleepPnl.add(mainAddSleepBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 100));

        mainViewSumBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainViewSumBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mainViewSumBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainViewSumBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/graph.png"))); // NOI18N
        mainViewSumBtn.setText("View Summary");
        mainViewSumBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        mainViewSumBtn.setBorderPainted(false);
        mainViewSumBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainViewSumBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainViewSumBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainViewSumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainViewSumBtnActionPerformed(evt);
            }
        });
        mainSleepPnl.add(mainViewSumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, 100));

        mainBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        mainBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        mainBackBtn.setText("Main Menu");
        mainBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        mainBackBtn.setBorderPainted(false);
        mainBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBackBtnActionPerformed(evt);
            }
        });
        mainSleepPnl.add(mainBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 30));

        addSleepPnl.setBackground(new java.awt.Color(210, 244, 234));
        addSleepPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addSleepPnl.setForeground(new java.awt.Color(0, 102, 51));
        addSleepPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        addSleepPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        addSleepPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSleepTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addSleepTitleLbl.setForeground(new java.awt.Color(0, 102, 0));
        addSleepTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/sleep.png"))); // NOI18N
        addSleepTitleLbl.setText("Sleep Tracker");
        addSleepPnl.add(addSleepTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        addDateLbl.setBackground(new java.awt.Color(204, 204, 255));
        addDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/calendar.png"))); // NOI18N
        addDateLbl.setText("DATE: ");
        addSleepPnl.add(addDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, -1));

        addSleepTimeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSleepTimeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/enoughsleep.png"))); // NOI18N
        addSleepTimeLbl.setText("Sleep Time: ");
        addSleepTimeLbl.setMaximumSize(new java.awt.Dimension(84, 25));
        addSleepTimeLbl.setMinimumSize(new java.awt.Dimension(84, 25));
        addSleepTimeLbl.setPreferredSize(new java.awt.Dimension(84, 25));
        addSleepPnl.add(addSleepTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, -1));

        addWakeTimeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addWakeTimeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/wakeup.png"))); // NOI18N
        addWakeTimeLbl.setText("Wake Time:");
        addWakeTimeLbl.setMaximumSize(new java.awt.Dimension(84, 25));
        addWakeTimeLbl.setMinimumSize(new java.awt.Dimension(84, 25));
        addWakeTimeLbl.setPreferredSize(new java.awt.Dimension(84, 25));
        addSleepPnl.add(addWakeTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        addDurationLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDurationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/hourglass.png"))); // NOI18N
        addDurationLbl.setText("Duration (Hrs): ");
        addDurationLbl.setMaximumSize(new java.awt.Dimension(84, 25));
        addDurationLbl.setMinimumSize(new java.awt.Dimension(84, 25));
        addDurationLbl.setPreferredSize(new java.awt.Dimension(84, 25));
        addSleepPnl.add(addDurationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, -1));

        addDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateFieldActionPerformed(evt);
            }
        });
        addSleepPnl.add(addDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, -1));
        addSleepPnl.add(addSleepTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, -1));
        addSleepPnl.add(addWakeTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));

        addDurationField.setEnabled(false);
        addSleepPnl.add(addDurationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, -1));

        addSaveBtn.setBackground(new java.awt.Color(142, 218, 114));
        addSaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSaveBtn.setForeground(new java.awt.Color(0, 102, 51));
        addSaveBtn.setText("Save");
        addSaveBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        addSaveBtn.setBorderPainted(false);
        addSleepPnl.add(addSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 70, 30));

        addBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        addBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        addBackBtn.setText("Back");
        addBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        addBackBtn.setBorderPainted(false);
        addBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBackBtnActionPerformed(evt);
            }
        });
        addSleepPnl.add(addBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 30));

        viewSleepPnl.setBackground(new java.awt.Color(210, 244, 234));
        viewSleepPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        viewSleepPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        viewSleepPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewSumLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewSumLbl.setForeground(new java.awt.Color(0, 102, 0));
        viewSumLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/dashboard.png"))); // NOI18N
        viewSumLbl.setText("Sleep Summary");
        viewSleepPnl.add(viewSumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, -1));

        viewSleepTablePnl.setLayout(new java.awt.BorderLayout());

        sleepTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Sleep Time", "Wake Time", "Duration"
            }
        ));
        jScrollPane1.setViewportView(sleepTbl);

        viewSleepTableScrollP.setViewportView(jScrollPane1);

        viewSleepTablePnl.add(viewSleepTableScrollP, java.awt.BorderLayout.CENTER);

        viewSleepPnl.add(viewSleepTablePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 130));

        viewSleepSumPnl.setBackground(new java.awt.Color(255, 255, 255));

        viewAvgSleepLbl.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        viewAvgSleepLbl.setText("Average Sleep (Hrs): ");

        viewAvgSleepField.setBorder(null);
        viewAvgSleepField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvgSleepFieldActionPerformed(evt);
            }
        });

        viewSleepHealthLbl.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        viewSleepHealthLbl.setText("Sleep Health: ");

        viewColorBarPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout viewColorBarPnlLayout = new javax.swing.GroupLayout(viewColorBarPnl);
        viewColorBarPnl.setLayout(viewColorBarPnlLayout);
        viewColorBarPnlLayout.setHorizontalGroup(
            viewColorBarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        viewColorBarPnlLayout.setVerticalGroup(
            viewColorBarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viewSleepSumPnlLayout = new javax.swing.GroupLayout(viewSleepSumPnl);
        viewSleepSumPnl.setLayout(viewSleepSumPnlLayout);
        viewSleepSumPnlLayout.setHorizontalGroup(
            viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                .addGroup(viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                        .addComponent(viewAvgSleepLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewAvgSleepField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(viewColorBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewSleepHealthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        viewSleepSumPnlLayout.setVerticalGroup(
            viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSleepSumPnlLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(viewSleepSumPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAvgSleepLbl)
                    .addComponent(viewAvgSleepField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewSleepHealthLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewColorBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        viewSleepPnl.add(viewSleepSumPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 400, 90));

        viewTipBtn.setBackground(new java.awt.Color(142, 218, 114));
        viewTipBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewTipBtn.setForeground(new java.awt.Color(0, 102, 51));
        viewTipBtn.setText("Sleep Tip");
        viewTipBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        viewTipBtn.setBorderPainted(false);
        viewTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTipBtnActionPerformed(evt);
            }
        });
        viewSleepPnl.add(viewTipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 110, -1));

        viewBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        viewBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        viewBackBtn.setText("Back");
        viewBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        viewBackBtn.setBorderPainted(false);
        viewBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBackBtnActionPerformed(evt);
            }
        });
        viewSleepPnl.add(viewBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, -1));

        showTipPnl.setBackground(new java.awt.Color(210, 244, 234));
        showTipPnl.setMinimumSize(new java.awt.Dimension(425, 371));
        showTipPnl.setPreferredSize(new java.awt.Dimension(425, 371));
        showTipPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showTipTitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        showTipTitleLbl.setForeground(new java.awt.Color(0, 102, 0));
        showTipTitleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepapp/lamp.png"))); // NOI18N
        showTipTitleLbl.setText("Sleep Tip");
        showTipPnl.add(showTipTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 210, 50));

        showTipArea.setEditable(false);
        showTipArea.setColumns(20);
        showTipArea.setLineWrap(true);
        showTipArea.setRows(5);
        showTipArea.setWrapStyleWord(true);
        showTipScrollP.setViewportView(showTipArea);

        showTipPnl.add(showTipScrollP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 380, 100));

        showAnotherTipBtn.setBackground(new java.awt.Color(142, 218, 114));
        showAnotherTipBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showAnotherTipBtn.setForeground(new java.awt.Color(0, 102, 51));
        showAnotherTipBtn.setText("Show Another Tip");
        showAnotherTipBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        showAnotherTipBtn.setBorderPainted(false);
        showTipPnl.add(showAnotherTipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 50));

        showBackBtn.setBackground(new java.awt.Color(142, 218, 114));
        showBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showBackBtn.setForeground(new java.awt.Color(0, 102, 51));
        showBackBtn.setText("Back");
        showBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        showBackBtn.setBorderPainted(false);
        showBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBackBtnActionPerformed(evt);
            }
        });
        showTipPnl.add(showBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(showTipPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addSleepPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewSleepPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(showTipPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainViewSumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainViewSumBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(true);

    }//GEN-LAST:event_mainViewSumBtnActionPerformed

    private void viewAvgSleepFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvgSleepFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAvgSleepFieldActionPerformed

    private void addDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDateFieldActionPerformed

    private void mainAddSleepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddSleepBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(false);
        addSleepPnl.setVisible(true);

    }//GEN-LAST:event_mainAddSleepBtnActionPerformed

    private void viewBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBackBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(true);
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);
    }//GEN-LAST:event_viewBackBtnActionPerformed

    private void addBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBackBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(true);
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);

    }//GEN-LAST:event_addBackBtnActionPerformed

    private void showBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBackBtnActionPerformed
        // TODO add your handling code here:
        mainSleepPnl.setVisible(true);
        addSleepPnl.setVisible(false);
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(false);
    }//GEN-LAST:event_showBackBtnActionPerformed

    private void viewTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTipBtnActionPerformed
        // TODO add your handling code here:
        viewSleepPnl.setVisible(false);
        showTipPnl.setVisible(true);

    }//GEN-LAST:event_viewTipBtnActionPerformed

    private void mainBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBackBtnActionPerformed
        // TODO add your handling code here:
        mainmenu.MainMenuGUI mainMenu= new mainmenu.MainMenuGUI();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SleepGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBackBtn;
    private javax.swing.JTextField addDateField;
    private javax.swing.JLabel addDateLbl;
    private javax.swing.JTextField addDurationField;
    private javax.swing.JLabel addDurationLbl;
    private javax.swing.JButton addSaveBtn;
    private javax.swing.JPanel addSleepPnl;
    private javax.swing.JTextField addSleepTimeField;
    private javax.swing.JLabel addSleepTimeLbl;
    private javax.swing.JLabel addSleepTitleLbl;
    private javax.swing.JTextField addWakeTimeField;
    private javax.swing.JLabel addWakeTimeLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainAddSleepBtn;
    private javax.swing.JButton mainBackBtn;
    private javax.swing.JPanel mainSleepPnl;
    private javax.swing.JLabel mainSubTitleLbl;
    private javax.swing.JLabel mainTitleLbl;
    private javax.swing.JButton mainViewSumBtn;
    private javax.swing.JButton showAnotherTipBtn;
    private javax.swing.JButton showBackBtn;
    private javax.swing.JTextArea showTipArea;
    private javax.swing.JPanel showTipPnl;
    private javax.swing.JScrollPane showTipScrollP;
    private javax.swing.JLabel showTipTitleLbl;
    private javax.swing.JTable sleepTbl;
    private javax.swing.JTextField viewAvgSleepField;
    private javax.swing.JLabel viewAvgSleepLbl;
    private javax.swing.JButton viewBackBtn;
    private javax.swing.JPanel viewColorBarPnl;
    private javax.swing.JLabel viewSleepHealthLbl;
    private javax.swing.JPanel viewSleepPnl;
    private javax.swing.JPanel viewSleepSumPnl;
    private javax.swing.JPanel viewSleepTablePnl;
    private javax.swing.JScrollPane viewSleepTableScrollP;
    private javax.swing.JLabel viewSumLbl;
    private javax.swing.JButton viewTipBtn;
    // End of variables declaration//GEN-END:variables
}
