/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exerciseapp;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dhruva
 */
public class ExerciseGUI extends javax.swing.JFrame {

    private ArrayList<Exercise> exercises ;//declaring the arraylist
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExerciseGUI.class.getName());
    private String name;
    private double calories, duration;
    /**
     * Creates new form ExerciseGUI
     */
    public ExerciseGUI() {
        exercises = new ArrayList<>();//creating a arraylist
        name=null;
        calories=0.0;
        duration=0;
        initComponents();
        addPanel.setVisible(false);
        displayPanel.setVisible(false);
        intensityLbl.setVisible(false);
        intensityCmb.setVisible(false);
        setsLbl.setVisible(false);
        setsTF.setVisible(false);
        repsLbl.setVisible(false);
        repsTF.setVisible(false);
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        displayBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        textLbl = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        titleALbl = new javax.swing.JLabel();
        nameALbl = new javax.swing.JLabel();
        nameATF = new javax.swing.JTextField();
        durationALbl = new javax.swing.JLabel();
        durationATF = new javax.swing.JTextField();
        typeALbl = new javax.swing.JLabel();
        cardioARB = new javax.swing.JRadioButton();
        strengthARB = new javax.swing.JRadioButton();
        caloriesALbl = new javax.swing.JLabel();
        caloriesATF = new javax.swing.JTextField();
        saveABtn = new javax.swing.JButton();
        backABtn = new javax.swing.JButton();
        textALbl = new javax.swing.JLabel();
        clearABtn = new javax.swing.JButton();
        displayABtn = new javax.swing.JButton();
        intensityCmb = new javax.swing.JComboBox<>();
        intensityLbl = new javax.swing.JLabel();
        setsLbl = new javax.swing.JLabel();
        setsTF = new javax.swing.JTextField();
        repsLbl = new javax.swing.JLabel();
        repsTF = new javax.swing.JTextField();
        addABtn = new javax.swing.JButton();
        minLbl = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        titleDLbl = new javax.swing.JLabel();
        backDBtn = new javax.swing.JButton();
        textDLbl = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        scrollDTA = new javax.swing.JScrollPane();
        textDTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(210, 244, 234));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(425, 371));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 51));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("  Exercise Tracker");

        displayBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(0, 102, 51));
        displayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exerciseapp/images/DISPLAY.png"))); // NOI18N
        displayBtn.setText(" Display Progress");
        displayBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 2, true));
        displayBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displayBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        displayBtn.setIconTextGap(8);
        displayBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        displayBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 102, 51));
        backBtn.setText(" Back to Main Page");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 76), 2));

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 102, 51));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exerciseapp/images/ADD.png"))); // NOI18N
        addBtn.setText("Add Exercise");
        addBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 156, 76), 2, true));
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBtn.setIconTextGap(8);
        addBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        textLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        textLbl.setForeground(new java.awt.Color(51, 51, 51));
        textLbl.setText("Keep your body active everyday");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(75, 75, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textLbl))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLbl)
                .addGap(48, 48, 48)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        addPanel.setBackground(new java.awt.Color(210, 244, 234));
        addPanel.setPreferredSize(new java.awt.Dimension(425, 371));

        titleALbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleALbl.setForeground(new java.awt.Color(0, 102, 51));
        titleALbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleALbl.setText(" Add New Exercise");

        nameALbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        nameALbl.setForeground(new java.awt.Color(51, 51, 51));
        nameALbl.setText("Exercise Name:");
        nameALbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameALbl.setMaximumSize(new java.awt.Dimension(0, 0));
        nameALbl.setMinimumSize(new java.awt.Dimension(0, 0));

        nameATF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nameATF.setHighlighter(null);

        durationALbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        durationALbl.setForeground(new java.awt.Color(51, 51, 51));
        durationALbl.setText("Duration: ");
        durationALbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        durationALbl.setMaximumSize(new java.awt.Dimension(0, 0));
        durationALbl.setMinimumSize(new java.awt.Dimension(0, 0));

        durationATF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        durationATF.setHighlighter(null);

        typeALbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        typeALbl.setForeground(new java.awt.Color(51, 51, 51));
        typeALbl.setText("Type:");
        typeALbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        typeALbl.setMaximumSize(new java.awt.Dimension(0, 0));
        typeALbl.setMinimumSize(new java.awt.Dimension(0, 0));

        type.add(cardioARB);
        cardioARB.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cardioARB.setForeground(new java.awt.Color(0, 102, 51));
        cardioARB.setText("Cardio");
        cardioARB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardioARBActionPerformed(evt);
            }
        });

        type.add(strengthARB);
        strengthARB.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        strengthARB.setForeground(new java.awt.Color(0, 102, 51));
        strengthARB.setText("Strength");
        strengthARB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthARBActionPerformed(evt);
            }
        });

        caloriesALbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        caloriesALbl.setForeground(new java.awt.Color(51, 51, 51));
        caloriesALbl.setText("Calories Burned: ");

        caloriesATF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        caloriesATF.setHighlighter(null);
        caloriesATF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caloriesATFActionPerformed(evt);
            }
        });

        saveABtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveABtn.setForeground(new java.awt.Color(0, 102, 51));
        saveABtn.setText("Save");
        saveABtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        saveABtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveABtn.setFocusPainted(false);
        saveABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveABtnActionPerformed(evt);
            }
        });

        backABtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backABtn.setForeground(new java.awt.Color(0, 102, 51));
        backABtn.setText("Back");
        backABtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        backABtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backABtn.setFocusPainted(false);
        backABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backABtnActionPerformed(evt);
            }
        });

        textALbl.setBackground(new java.awt.Color(60, 60, 60));
        textALbl.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        textALbl.setText("\"Fill the details below to record your activity\"");

        clearABtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearABtn.setForeground(new java.awt.Color(0, 102, 51));
        clearABtn.setText("Clear");
        clearABtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        clearABtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearABtn.setFocusPainted(false);
        clearABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearABtnActionPerformed(evt);
            }
        });

        displayABtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayABtn.setForeground(new java.awt.Color(0, 102, 51));
        displayABtn.setText("Display");
        displayABtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        displayABtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displayABtn.setFocusPainted(false);
        displayABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayABtnActionPerformed(evt);
            }
        });

        intensityCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Medium", "Low", " " }));
        intensityCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensityCmbActionPerformed(evt);
            }
        });

        intensityLbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        intensityLbl.setForeground(new java.awt.Color(51, 51, 51));
        intensityLbl.setText("Intensity:");
        intensityLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        intensityLbl.setMaximumSize(new java.awt.Dimension(0, 0));
        intensityLbl.setMinimumSize(new java.awt.Dimension(0, 0));

        setsLbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        setsLbl.setForeground(new java.awt.Color(51, 51, 51));
        setsLbl.setText("Sets:");
        setsLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setsLbl.setMaximumSize(new java.awt.Dimension(0, 0));
        setsLbl.setMinimumSize(new java.awt.Dimension(0, 0));

        setsTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setsTF.setHighlighter(null);

        repsLbl.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        repsLbl.setForeground(new java.awt.Color(51, 51, 51));
        repsLbl.setText("Reps:");
        repsLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        repsLbl.setMaximumSize(new java.awt.Dimension(0, 0));
        repsLbl.setMinimumSize(new java.awt.Dimension(0, 0));

        repsTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        repsTF.setHighlighter(null);

        addABtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addABtn.setForeground(new java.awt.Color(0, 102, 51));
        addABtn.setText("Add");
        addABtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addABtn.setFocusPainted(false);
        addABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addABtnActionPerformed(evt);
            }
        });

        minLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        minLbl.setText("minutes");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(titleALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(textALbl))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeALbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationALbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intensityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(repsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameALbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(cardioARB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(strengthARB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(intensityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(durationATF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(nameATF, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minLbl))
                                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(repsTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(setsTF, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(caloriesALbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caloriesATF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(saveABtn)
                        .addGap(54, 54, 54)
                        .addComponent(clearABtn)
                        .addGap(46, 46, 46)
                        .addComponent(displayABtn)))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addABtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backABtn)
                .addGap(19, 19, 19))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleALbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textALbl)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(nameALbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationALbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeALbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardioARB)
                    .addComponent(strengthARB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intensityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intensityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backABtn)
                            .addComponent(displayABtn)
                            .addComponent(clearABtn)
                            .addComponent(saveABtn)
                            .addComponent(addABtn))
                        .addGap(12, 12, 12))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caloriesALbl)
                            .addComponent(caloriesATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(70, Short.MAX_VALUE))))
        );

        nameALbl.getAccessibleContext().setAccessibleName("null");
        durationALbl.getAccessibleContext().setAccessibleName("null");
        typeALbl.getAccessibleContext().setAccessibleName("null");
        intensityLbl.getAccessibleContext().setAccessibleName("null");
        setsLbl.getAccessibleContext().setAccessibleName("null");
        repsLbl.getAccessibleContext().setAccessibleName("null");

        displayPanel.setBackground(new java.awt.Color(210, 244, 234));
        displayPanel.setPreferredSize(new java.awt.Dimension(425, 371));

        titleDLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleDLbl.setForeground(new java.awt.Color(0, 102, 51));
        titleDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDLbl.setText(" Display all Exercises");

        backDBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backDBtn.setForeground(new java.awt.Color(0, 102, 51));
        backDBtn.setText("Back");
        backDBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 1, true));
        backDBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDBtnActionPerformed(evt);
            }
        });

        textDLbl.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        textDLbl.setForeground(new java.awt.Color(60, 60, 60));
        textDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDLbl.setText("Here's your progress summary");

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(0, 102, 51));
        clearBtn.setText("Clear");
        clearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 76), 1, true));
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        scrollDTA.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));

        textDTA.setEditable(false);
        textDTA.setColumns(40);
        textDTA.setForeground(new java.awt.Color(0, 152, 76));
        textDTA.setRows(15);
        scrollDTA.setViewportView(textDTA);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(backDBtn)
                        .addGap(73, 73, 73)
                        .addComponent(clearBtn))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(scrollDTA, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(scrollDTA, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtn)
                    .addComponent(backDBtn))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(displayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // Method to save all the exercises into a .dat file
    private void save(){
        try(ObjectOutputStream oStream= new ObjectOutputStream(new FileOutputStream("exercise.dat"))){
            oStream.writeObject(exercises);  //writes the entire arraylist to a file   
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error: "+ e.getMessage());
        }
    }
    //Method to load all the saved exercises when the app starts
    private void load(){
        try(ObjectInputStream oStream= new ObjectInputStream(new FileInputStream("exercise.dat"))){
           exercises=(ArrayList<Exercise>) oStream.readObject(); //read the all saved exercises in arraylist from the file
           
        }
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(this,"The data file exercise.dat was not found. Please save before trying to load.");
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(this, "Load Error: "+ e.getMessage());
        }
        catch(IOException e){
           JOptionPane.showMessageDialog(this, "Load Error: "+ e.getMessage());  
        }
    }
    //Method to show all saved exercises in the textarea
    private void display(){
        textDTA.setText(""); //clear the old exercise from text area
        if(exercises.isEmpty()){ //if there is no exercise, display a message
            textDTA.setText("No Exercise to display");
        }
        else {// loop through each exercise that are stored in arraylist
            for(int i=0;i<exercises.size();i++){
                Exercise e= exercises.get(i);
                    textDTA.append(e.printDetails()+"\n\n");// add the exercise in text area
                
            }
            
        }
    }
    private void cardioARBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardioARBActionPerformed
        // TODO add your handling code here:
        //Display only cardio-specific fields
        intensityLbl.setVisible(true);
        intensityCmb.setVisible(true);

        // Hide strength-specific fields
        setsLbl.setVisible(false);
        setsTF.setVisible(false);
        repsLbl.setVisible(false);
        repsTF.setVisible(false);
    }//GEN-LAST:event_cardioARBActionPerformed

    private void backABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backABtnActionPerformed
        // TODO add your handling code here:
        addPanel.setVisible(false);
        mainPanel.setVisible(true);


    }//GEN-LAST:event_backABtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.setVisible(false);
        addPanel.setVisible(true);

    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.setVisible(false);
        displayPanel.setVisible(true);
        display();//method that display all the saved exercise

    }//GEN-LAST:event_displayBtnActionPerformed

    private void backDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDBtnActionPerformed
        // TODO add your handling code here:
        displayPanel.setVisible(false);
        mainPanel.setVisible(true);
        addPanel.setVisible(false);

    }//GEN-LAST:event_backDBtnActionPerformed

    private void strengthARBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthARBActionPerformed
        // TODO add your handling code here:
        //Hide the cardio-specific fields
        intensityLbl.setVisible(false);
        intensityCmb.setVisible(false);

        // Show strength-specific fields
        setsLbl.setVisible(true);
        setsTF.setVisible(true);
        repsLbl.setVisible(true);
        repsTF.setVisible(true);
    }//GEN-LAST:event_strengthARBActionPerformed

    private void displayABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayABtnActionPerformed
        // TODO add your handling code here:
        addPanel.setVisible(false);      // hide Add panel
        displayPanel.setVisible(true);   // show Display panel
        display();//method that display all the saved exercices
    }//GEN-LAST:event_displayABtnActionPerformed

    private void clearABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearABtnActionPerformed
        // TODO add your handling code here:
        nameATF.setText("");
        durationATF.setText("");
        caloriesATF.setText("");
        type.clearSelection();  // unselect both radio buttons
        setsTF.setText("");
        repsTF.setText("");
        
    }//GEN-LAST:event_clearABtnActionPerformed

    private void intensityCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensityCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensityCmbActionPerformed

    private void saveABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveABtnActionPerformed
        // TODO add your handling code here:
        save();// method that saves the entered exercise
        JOptionPane.showMessageDialog(this, "Exercise Added Successfully");
    }//GEN-LAST:event_saveABtnActionPerformed
    //Method that adds the exercise when the user click add button 
    private void addABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addABtnActionPerformed
        // TODO add your handling code here:
        
        try{
             name= nameATF.getText();// getting the name from the text field
             duration= Double.parseDouble(durationATF.getText());
            if(cardioARB.isSelected()){// if the cardio button is selected 
                String intensity=intensityCmb.getSelectedItem().toString();// converting the selection to string
                Cardio c= new Cardio(intensity, name, duration);
                 calories= c.calculateCalories();//calculating the calroies
                 exercises.add(c);//add the cardio object to arraylist
                
            }
            else if(strengthARB.isSelected()){ //if strength is selected 
                int sets=Integer.parseInt(setsTF.getText());
                int reps=Integer.parseInt(repsTF.getText());
                Strength s = new Strength(sets, reps, name, duration);
                calories= s.calculateCalories();
                exercises.add(s);
            }
            else{
                caloriesATF.setText("Select a type!");
                return;
            }
            caloriesATF.setText(String.format("%.2f", calories));// converting the string into double to get it displayed
        }
        catch(Exception e){
            caloriesATF.setText("Error");
        }
    }//GEN-LAST:event_addABtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
         String choice=JOptionPane.showInputDialog(this, "Are you sure want to clear your progress?");
        if (choice.equalsIgnoreCase("yes")){
        exercises.clear(); //clears the arraylist 
        textDTA.setText(""); // clears the text field
        save(); //saves the empty list to the file 
        JOptionPane.showMessageDialog(this, "File cleared Successfully");
       
        }
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void caloriesATFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caloriesATFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_caloriesATFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExerciseGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addABtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton backABtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backDBtn;
    private javax.swing.JLabel caloriesALbl;
    private javax.swing.JTextField caloriesATF;
    private javax.swing.JRadioButton cardioARB;
    private javax.swing.JButton clearABtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton displayABtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel durationALbl;
    private javax.swing.JTextField durationATF;
    private javax.swing.JComboBox<String> intensityCmb;
    private javax.swing.JLabel intensityLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel minLbl;
    private javax.swing.JLabel nameALbl;
    private javax.swing.JTextField nameATF;
    private javax.swing.JLabel repsLbl;
    private javax.swing.JTextField repsTF;
    private javax.swing.JButton saveABtn;
    private javax.swing.JScrollPane scrollDTA;
    private javax.swing.JLabel setsLbl;
    private javax.swing.JTextField setsTF;
    private javax.swing.JRadioButton strengthARB;
    private javax.swing.JLabel textALbl;
    private javax.swing.JLabel textDLbl;
    private javax.swing.JTextArea textDTA;
    private javax.swing.JLabel textLbl;
    private javax.swing.JLabel titleALbl;
    private javax.swing.JLabel titleDLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup type;
    private javax.swing.JLabel typeALbl;
    // End of variables declaration//GEN-END:variables
}
